# Generated by Django 3.2.9 on 2021-11-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='public',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=250),
        ),
    ]
